name: 'Setup Environment'
description: 'Sets up Node.js, pnpm and installs dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '16'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.6.0
        
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile