#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run linters before committing
npx solhint 'contracts/**/*.sol'
# Run test coverage with fallback mechanism to handle stack too deep errors
node scripts/coverage-check-wrapper.js
