name: TicketChain CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Compile contracts
        run: npm run compile
      - name: Run linter
        run: npm run lint
      - name: Run unit tests
        run: npm run test
      - name: Run integration tests
        run: npm run test:integration
      - name: Run coverage
        run: npm run test:coverage
      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts-artifacts
          path: |
            artifacts/contracts
            !artifacts/contracts/mocks
            deployments

  deploy-testnet:
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Setup environment
        run: |
          echo "INFURA_API_KEY=${{ secrets.INFURA_API_KEY }}" >> .env
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
          echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env
      - name: Compile contracts
        run: npm run compile
      - name: Deploy to testnet
        run: npm run deploy:testnet
